version: '2.1'

services:
  agent:
    image: golang:1.20
    volumes:
      - go-module-cache:/go/pkg/mod
      - ../:/cli:cached
    working_dir: /cli
    environment:
      - GO111MODULE=on
  go:
    build:
      context: .
    volumes:
      - .:/work
    working_dir: /work
    environment:
      - BUILDKITE_ANALYTICS_TOKEN
      - BUILDKITE_API_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_JOB_ID
      - BUILDKITE_MESSAGE
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_TAG
      - GITHUB_TOKEN
      - GPG_SECRET_KEY_BASE64

volumes:
  go-module-cache:
