steps:
  - name: "Lint"
    command: ".buildkite/steps/lint.sh"
    plugins:
      docker#v3.5.0:
        image: "golang:1.20"

  - name: "Test"
    command: "go test -v -failfast ./..."
    plugins:
      docker-compose#v3.0.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait
  - name: "Test with Local Agent"
    command: ".buildkite/steps/run-local.sh"
    plugins:
      docker-compose#v3.0.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait
  - label: ":golang:"
    plugins:
      golang-cross-compile#v1.3.0:
        build: ./cmd/bk
        import: github.com/buildkite/cli/v2
        targets:
          - version: "1.20.0"
            goos: darwin
            goarch: amd64
          - version: "1.20.0"
            goos: darwin
            goarch: arm64
          - version: "1.20.0"
            goos: linux
            goarch: amd64
          - version: "1.20.0"
            goos: linux
            goarch: arm64
          - version: "1.20.0"
            goos: windows
            goarch: amd64
  - block: Release?
  - label: 🚀 Release BK CLI
    command: ".buildkite/steps/release.sh"
    plugins:
      - ecr#v2.3.0:
          account-ids: "502722253770"
          login: true
      - docker-compose#v2.2.0:
          run: go
