steps:
  - name: "Lint"
    command: ".buildkite/steps/lint.sh"
    plugins:
      docker#v5.8.0:
        image: "golang:1.20"

  - name: "Test"
    command: "go test -v -failfast ./..."
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait
  - name: "Test with Local Agent"
    command: ".buildkite/steps/run-local.sh"
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait
  - label: ":golang:"
    command: make build
    plugins:
      golang#v2.0.0:
        version: 1.20.0
        environment:
          - RELEVANCE_API_URL
          - RELEVANCE_PROJECT
    artifact_paths:
      - "build/*"
  - block: Release?
  - label: 🚀 Release BK CLI
    command: ".buildkite/steps/release.sh"
    plugins:
      - ecr#v2.3.0:
          account-ids: "502722253770"
          login: true
      - docker-compose#v2.2.0:
          run: go
